# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:\\Users\\TRUONG HUU\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\PyQt5\\Qt5\\plugins\\platforms'

class Ui_caesar(object):  # Ensure class name matches
    def setupUi(self, caesar):
        caesar.setObjectName("caesar")
        caesar.resize(803, 431)
        caesar.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(caesar)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 20, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 240, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 60, 581, 87))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 230, 581, 87))
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 180, 581, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 340, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 340, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        caesar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(caesar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 26))
        self.menubar.setObjectName("menubar")
        caesar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(caesar)
        self.statusbar.setObjectName("statusbar")
        caesar.setStatusBar(self.statusbar)

        self.retranslateUi(caesar)
        QtCore.QMetaObject.connectSlotsByName(caesar)

    def retranslateUi(self, caesar):
        _translate = QtCore.QCoreApplication.translate
        caesar.setWindowTitle(_translate("caesar", "Caesar Cipher"))
        self.label.setText(_translate("caesar", "CAESAR CIPHER"))
        self.label_2.setText(_translate("caesar", "Plain Text:"))
        self.label_3.setText(_translate("caesar", "Key:"))
        self.label_4.setText(_translate("caesar", "Cipher Text:"))
        self.pushButton.setText(_translate("caesar", "Encrypt"))
        self.pushButton_2.setText(_translate("caesar", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    caesar = QtWidgets.QMainWindow()
    ui = Ui_caesar()
    ui.setupUi(caesar)
    caesar.show()
    sys.exit(app.exec_())
